name: CI-Test

on: 
 push:
   branches:
     - main
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Xcode
      run: sudo xcode-select --switch /Applications/Xcode_14.2.app
    - name: build test
      run: |
           xcodebuild -project GHFollowers.xcodeproj \
                    -scheme GHFollowers \
                    -destination 'platform=iOS Simulator,name=iPhone 12' \
                    clean build test
