name: CI-Test

on: 
 push:
   branches:[main]
jobs:
  build:
    runs-on: macos-latest          
      - name: Build app
        run: xcodebuild -project GHFollowers.xcodeproj -scheme GHFollowers -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14 Pro'
