name: CI-Test

on: 
 push:
   branches:
     - main
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Xcode
      run: sudo xcode-select --switch /Applications/Xcode_14.2.app
    - name: Install certification and Profile
      env: 
           BUILD_CERTIFICATION_BASE64: ${{secrets.CICD_DIS_CER}}
           P12_PASSWORD: ${{secrets.CICD_PWD}}
           KEYCHAIN_PWD: ${{secrets.CICD_KEYCHAIN_PWD}}
           BUILD_PROFILE_BASE64: ${{secrets.CICD_PRO_DIS}}
      run: |
        #create variable
        echo $RUNNER_TEMP
        CERTIFICATION_PATH=$RUNNER_TEMP/build_certification.p12
        PROFILE_PATH=$RUNNER_TEMP/build_pp.mobileprovision
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
        # import certificate and provisioning profile from secrets
        echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATION_PATH
        echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PROFILE_PATH
        # create temporary keychain
        security create-keychain -p "$KEYCHAIN_PWD" $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p "$KEYCHAIN_PWD" $KEYCHAIN_PATH

    - name: build test
      run: |
           xcodebuild -project GHFollowers.xcodeproj \
                    -scheme GHFollowers \
                    -destination 'platform=iOS Simulator,name=iPhone 12' \
                    clean build
