name: CI-Test

on: 
 push:
   branches:[main]
jobs:
  build:
    runs-on: macos-10.13.1
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Xcode
      run: sudo xcode-select --switch /Applications/Xcode_14.2.app
    - name: Print GitHub Actions environment variables
       run: |
           env
    - name: build test 
       run: xcodebuild -project GHFollowers.xcodeproj  -scheme GHFollowers -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14'
